# Generated by Django 6.1.1 on 2026-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('shopping', 'Shopping'), ('ideas', 'Ideas'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
