# Generated by Django 6.1.1 on 2026-09-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='recurrence',
            field=models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurrence_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
